### PR TITLE
Fix libvdpau_sunxi.so link error No such file or directory

### PR DESCRIPTION
**Pull request by xchetah**
Fix error : 
Failed to open VDPAU backend libvdpau_sunxi.so: cannot open shared object file: No such file or directory

### CODE REVIEW

**Comment by mosterta** [comment]
Thanks for the pull request. Unfortunately I guess this is not the correct fix; the hardware specific lib libvdpau_sunxi.so is expected to be in the $(MODULEDIR) and the link is only there to create a libvdpau_sunxi.so.1 from libvdpau_sunxi.so, not to link the library from $(MODULEDIR) to /usr/lib

Any comment?

**Comment by xchetah** [comment]
Well, without this edit , sudo make install creates /usr/lib/libvdpau_sunxi.so symlink , which points only to libvdpau_sunxi.so.1 (in the same dir i.e. /usr/lib) instead of pointing to /usr/lib/vdpau/libvdpau_sunxi.so.1 , thus always gives the error that libvdpau_sunxi.so No such file or directory.
Could you please test this on a clean installation, or deleting all available libvdpau_sunxi* in /usr directory, 
Thanks

**Comment by mosterta** [comment]
have you checked my last commits?
I have changed the installation and the link should be created correct now

**Comment by xchetah** [comment]
Ok great thanks!

**Pull request closed without merging**
